oname: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t creativehub .

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GH_REGISTRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker image
        run: docker tag creativehub ghcr.io/venkateshdocker1/creativehub:latest

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/GitGuru4DevOps-Venkatesh/creativehub:latest
